# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adduser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_addUserForm(object):
    def setupUi(self, addUserForm):
        addUserForm.setObjectName("addUserForm")
        addUserForm.resize(400, 400)
        addUserForm.setMinimumSize(QtCore.QSize(400, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        addUserForm.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(addUserForm)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(addUserForm)
        self.frame.setStyleSheet("background-color: rgba(245, 245, 245， 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.nameEdit = QtWidgets.QLineEdit(self.frame)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.nameEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.nameEdit.setFont(font)
        self.nameEdit.setObjectName("nameEdit")
        self.horizontalLayout_2.addWidget(self.nameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.passwordEdit = QtWidgets.QLineEdit(self.frame)
        self.passwordEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.passwordEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.passwordEdit.setFont(font)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout.addWidget(self.passwordEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.addUserBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.addUserBtn.setFont(font)
        self.addUserBtn.setObjectName("addUserBtn")
        self.verticalLayout.addWidget(self.addUserBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(addUserForm)
        QtCore.QMetaObject.connectSlotsByName(addUserForm)

    def retranslateUi(self, addUserForm):
        _translate = QtCore.QCoreApplication.translate
        addUserForm.setWindowTitle(_translate("addUserForm", "添加用户"))
        self.label.setText(_translate("addUserForm", "用户名"))
        self.label_2.setText(_translate("addUserForm", "密码"))
        self.addUserBtn.setText(_translate("addUserForm", "确认添加"))
