# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import STATUS.resources

class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(600, 400)
        loginForm.setMinimumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        loginForm.setFont(font)
        loginForm.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(loginForm)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(loginForm)
        self.frame_2.setStyleSheet("#frame_2{border-image: url(:/resources/common/bg-3.jpg);}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setStyleSheet("background-color: rgba(245, 245, 245,150);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(245, 245, 245, 200);\n"
"color: rgb(0, 0, 0);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sessionTbl = QtWidgets.QTableWidget(self.frame)
        self.sessionTbl.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.sessionTbl.setFont(font)
        self.sessionTbl.setStyleSheet("background-color: rgba(245, 245, 245, 200);")
        self.sessionTbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sessionTbl.setColumnCount(6)
        self.sessionTbl.setObjectName("sessionTbl")
        self.sessionTbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(5, item)
        self.sessionTbl.horizontalHeader().setCascadingSectionResizes(False)
        self.sessionTbl.horizontalHeader().setHighlightSections(False)
        self.sessionTbl.horizontalHeader().setSortIndicatorShown(False)
        self.sessionTbl.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.sessionTbl)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")






        self.NewBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.NewBtn.setFont(font)
        self.NewBtn.setObjectName("connectBtn")
        self.horizontalLayout.addWidget(self.NewBtn)

        self.delBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.delBtn.setFont(font)
        self.delBtn.setObjectName("connectBtn")
        self.horizontalLayout.addWidget(self.delBtn)


        self.connectBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName("connectBtn")
        self.horizontalLayout.addWidget(self.connectBtn)


        self.closeBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.closeBtn.setFont(font)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)


        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout_3.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Log in"))
        self.label.setText(_translate("loginForm", "所有会话"))
        item = self.sessionTbl.horizontalHeaderItem(0)
        item.setText(_translate("loginForm", "名称"))
        item = self.sessionTbl.horizontalHeaderItem(1)
        item.setText(_translate("loginForm", "用户名"))
        item = self.sessionTbl.horizontalHeaderItem(2)
        item.setText(_translate("loginForm", "协议"))
        item = self.sessionTbl.horizontalHeaderItem(3)
        item.setText(_translate("loginForm", "端口"))
        item = self.sessionTbl.horizontalHeaderItem(4)
        item.setText(_translate("loginForm", "主机"))
        item = self.sessionTbl.horizontalHeaderItem(5)
        item.setText(_translate("loginForm", "口令"))
        self.NewBtn.setText(_translate("loginForm","新建"))
        self.delBtn.setText(_translate("loginForm","删除"))
        self.connectBtn.setText(_translate("loginForm", "连接"))
        self.closeBtn.setText(_translate("loginForm", "关闭"))

