# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginForm(object):
    def setupUi(self, loginForm):
        loginForm.setObjectName("loginForm")
        loginForm.resize(621, 419)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        loginForm.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(loginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(loginForm)
        self.label.setStyleSheet("background-color: rgba(245, 245, 245, 200);")
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.sessionTbl = QtWidgets.QTableWidget(loginForm)
        self.sessionTbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.sessionTbl.setColumnCount(6)
        self.sessionTbl.setObjectName("sessionTbl")
        self.sessionTbl.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sessionTbl.setHorizontalHeaderItem(5, item)
        self.sessionTbl.horizontalHeader().setCascadingSectionResizes(False)
        self.sessionTbl.horizontalHeader().setHighlightSections(False)
        self.sessionTbl.horizontalHeader().setSortIndicatorShown(False)
        self.sessionTbl.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.sessionTbl)
        self.frame = QtWidgets.QFrame(loginForm)
        self.frame.setStyleSheet("background-color: rgba(245, 245, 245, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(382, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.connectBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.connectBtn.setFont(font)
        self.connectBtn.setObjectName("connectBtn")
        self.horizontalLayout.addWidget(self.connectBtn)
        self.closeBtn = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.closeBtn.setFont(font)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout.addWidget(self.closeBtn)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(loginForm)
        QtCore.QMetaObject.connectSlotsByName(loginForm)

    def retranslateUi(self, loginForm):
        _translate = QtCore.QCoreApplication.translate
        loginForm.setWindowTitle(_translate("loginForm", "Log in"))
        self.label.setText(_translate("loginForm", "所有会话"))
        item = self.sessionTbl.horizontalHeaderItem(0)
        item.setText(_translate("loginForm", "名称"))
        item = self.sessionTbl.horizontalHeaderItem(1)
        item.setText(_translate("loginForm", "用户名"))
        item = self.sessionTbl.horizontalHeaderItem(2)
        item.setText(_translate("loginForm", "协议"))
        item = self.sessionTbl.horizontalHeaderItem(3)
        item.setText(_translate("loginForm", "端口"))
        item = self.sessionTbl.horizontalHeaderItem(4)
        item.setText(_translate("loginForm", "主机"))
        item = self.sessionTbl.horizontalHeaderItem(5)
        item.setText(_translate("loginForm", "口令"))
        self.connectBtn.setText(_translate("loginForm", "连接"))
        self.closeBtn.setText(_translate("loginForm", "关闭"))
